"""Export tests: CSV + XLSX service, API endpoint, CLI. Phase 7.

All assertions run against real generated bytes — CSV is parsed back, XLSX
is opened with openpyxl, the API is exercised through TestClient, and the
CLI writes a real file. Nothing here mocks the export service.
"""

from __future__ import annotations

import csv
import io
import time
from datetime import datetime

import pytest
from fastapi.testclient import TestClient
from openpyxl import load_workbook

from leadforge import cli as cli_module
from leadforge.db import session_scope
from leadforge.main import create_app
from leadforge.services import export as export_service

from .fixtures import make_company, make_job, make_result


@pytest.fixture
def client(engine):
    app = create_app(engine=engine)
    with TestClient(app) as test_client:
        yield test_client


def _completed_job_with_results(session, n=3, **job_kwargs):
    """A completed job with ``n`` deterministic results (some null fields)."""
    job_kwargs.setdefault("status", "completed")
    job = make_job(**job_kwargs)
    session.add(job)
    session.flush()
    for i in range(n):
        company = make_company(
            company_name=f"Export Test Co {i:02d}",
            normalized_name=f"export test co {i:02d}",
            website=f"https://export{i:02d}.example.com/",
            normalized_domain=f"export{i:02d}.example.com",
            source_url=f"https://export{i:02d}.example.com/",
            city="Los Angeles" if i % 2 == 0 else None,  # null field
            phone=None if i == 0 else f"+1-555-01{i:02d}",  # null field
            public_email=None if i == 1 else f"info@export{i:02d}.example.com",
            linkedin_url=None,  # always null in the demo world
            is_synthetic=(i != 2),  # one non-synthetic row for honesty checks
        )
        session.add(company)
        session.flush()
        result = make_result(
            job,
            company,
            quality_score=95 - i * 10,
            validation_status="valid" if i != 1 else "invalid",
        )
        session.add(result)
    session.commit()
    return job


# ---------------------------------------------------------------------------
# service: CSV
# ---------------------------------------------------------------------------


class TestExportCsv:
    def test_csv_has_bom_and_expected_headers(self, session):
        job = _completed_job_with_results(session)
        payload = export_service.render_csv(
            export_service.fetch_export_rows(session, job.id)
        )
        assert payload.startswith(b"\xef\xbb\xbf"), "CSV must start with a UTF-8 BOM"
        text = payload.decode("utf-8-sig")
        reader = csv.reader(io.StringIO(text))
        header = next(reader)
        assert header == list(export_service.EXPORT_COLUMNS)
        assert len(header) == 14
        assert "is_synthetic" in header

    def test_csv_rows_match_results(self, session):
        job = _completed_job_with_results(session, n=3)
        rows = export_service.fetch_export_rows(session, job.id)
        payload = export_service.render_csv(rows)
        parsed = list(csv.DictReader(io.StringIO(payload.decode("utf-8-sig"))))
        assert len(parsed) == 3
        assert parsed[0]["company_name"] == "Export Test Co 00"
        assert parsed[0]["quality_score"] == "95"
        assert parsed[0]["is_synthetic"] == "true"
        assert parsed[2]["is_synthetic"] == "false"
        assert parsed[1]["validation_status"] == "invalid"

    def test_csv_null_fields_become_empty(self, session):
        job = _completed_job_with_results(session, n=3)
        rows = export_service.fetch_export_rows(session, job.id)
        parsed = list(
            csv.DictReader(
                io.StringIO(export_service.render_csv(rows).decode("utf-8-sig"))
            )
        )
        assert parsed[0]["phone"] == ""  # null phone -> empty cell
        assert parsed[1]["public_email"] == ""  # null email -> empty cell
        assert parsed[0]["city"] == "Los Angeles"
        assert parsed[1]["city"] == ""  # null city -> empty cell
        # A valid CSV even with nulls: every row has 14 cells.
        for row in parsed:
            assert len(row) == 14

    def test_csv_is_deterministic(self, session):
        job = _completed_job_with_results(session, n=3)
        rows_a = export_service.fetch_export_rows(session, job.id)
        rows_b = export_service.fetch_export_rows(session, job.id)
        assert export_service.render_csv(rows_a) == export_service.render_csv(rows_b)

    def test_csv_zero_results_is_header_only(self, session):
        job = make_job(status="completed")
        session.add(job)
        session.commit()
        rows = export_service.fetch_export_rows(session, job.id)
        assert rows == []
        parsed = list(
            csv.reader(
                io.StringIO(export_service.render_csv(rows).decode("utf-8-sig"))
            )
        )
        assert len(parsed) == 1  # header only, still valid CSV
        assert parsed[0] == list(export_service.EXPORT_COLUMNS)


# ---------------------------------------------------------------------------
# service: XLSX
# ---------------------------------------------------------------------------


class TestExportXlsx:
    def _workbook(self, session, job):
        rows = export_service.fetch_export_rows(session, job.id)
        payload = export_service.render_xlsx(job, rows)
        return load_workbook(io.BytesIO(payload)), rows

    def test_xlsx_has_exactly_three_sheets(self, session):
        job = _completed_job_with_results(session)
        wb, _ = self._workbook(session, job)
        assert wb.sheetnames == ["Leads", "Research Summary", "Parameters"]

    def test_xlsx_leads_headers_and_data(self, session):
        job = _completed_job_with_results(session, n=3)
        wb, _ = self._workbook(session, job)
        ws = wb["Leads"]
        headers = [c.value for c in ws[1]]
        assert headers == list(export_service.XLSX_LEADS_COLUMNS)
        assert "is_synthetic" in headers
        # Data rows: company names, numeric scores, synthetic flags.
        names = [ws.cell(row=r, column=1).value for r in range(2, 5)]
        assert names == ["Export Test Co 00", "Export Test Co 01", "Export Test Co 02"]
        score_col = headers.index("quality_score") + 1
        scores = [ws.cell(row=r, column=score_col).value for r in range(2, 5)]
        assert scores == [95, 85, 75]
        assert all(isinstance(s, int) for s in scores), "score must be a number"
        synth_col = headers.index("is_synthetic") + 1
        assert [ws.cell(row=r, column=synth_col).value for r in range(2, 5)] == [
            True,
            True,
            False,
        ]
        band_col = headers.index("score_band") + 1
        assert [ws.cell(row=r, column=band_col).value for r in range(2, 5)] == [
            "High",
            "Medium",
            "Medium",
        ]

    def test_xlsx_source_url_is_hyperlink_and_date_formatted(self, session):
        job = _completed_job_with_results(session, n=2)
        wb, _ = self._workbook(session, job)
        ws = wb["Leads"]
        headers = [c.value for c in ws[1]]
        url_col = headers.index("source_url") + 1
        date_col = headers.index("collected_at") + 1
        url_cell = ws.cell(row=2, column=url_col)
        assert url_cell.hyperlink is not None
        assert url_cell.hyperlink.target == "https://export00.example.com/"
        date_cell = ws.cell(row=2, column=date_col)
        assert isinstance(date_cell.value, datetime)
        assert date_cell.number_format == "yyyy-mm-dd hh:mm:ss"

    def test_xlsx_styling_freeze_and_filter(self, session):
        job = _completed_job_with_results(session, n=2)
        wb, _ = self._workbook(session, job)
        ws = wb["Leads"]
        header = ws["A1"]
        assert header.font.bold is True
        assert header.fill.start_color.rgb.endswith("E5E7EB")
        assert header.border.bottom.style == "thin"
        assert ws.freeze_panes == "A2"
        assert ws.auto_filter.ref is not None
        # Parameters sheet carries the exact job inputs.
        params = wb["Parameters"]
        param_names = [params.cell(row=r, column=1).value for r in range(2, 11)]
        assert param_names == [
            "industry",
            "country",
            "region",
            "city",
            "keywords",
            "requested_leads",
            "provider",
            "enable_ai",
            "demo_delay_ms",
        ]
        assert params.cell(row=2, column=2).value == "Jewelry Stores"

    def test_xlsx_summary_sheet_totals(self, session):
        job = _completed_job_with_results(session, n=3)
        job.discovered = 10
        job.accepted = 3
        job.duplicates = 4
        job.invalid = 3
        session.commit()
        wb, _ = self._workbook(session, job)
        ws = wb["Research Summary"]
        summary = {
            ws.cell(row=r, column=1).value: ws.cell(row=r, column=2).value
            for r in range(3, ws.max_row + 1)
        }
        assert summary["Discovered"] == 10
        assert summary["Accepted"] == 3
        assert summary["Duplicates removed"] == 4
        assert summary["Invalid"] == 3
        assert summary["Average completeness"] == 85.0
        assert summary["Industry"] == "Jewelry Stores"

    def test_xlsx_leads_sheet_is_deterministic(self, session):
        job = _completed_job_with_results(session, n=2)
        rows = export_service.fetch_export_rows(session, job.id)
        first = export_service.render_xlsx(job, rows)
        second = export_service.render_xlsx(job, rows)
        # The summary sheet embeds an "Exported at" timestamp, so compare the
        # Leads sheet (the deterministic payload) rather than raw bytes.
        sheet1 = load_workbook(io.BytesIO(first))["Leads"]
        sheet2 = load_workbook(io.BytesIO(second))["Leads"]
        assert sheet1.dimensions == sheet2.dimensions
        assert [r for r in sheet1.iter_rows(values_only=True)] == [
            r for r in sheet2.iter_rows(values_only=True)
        ]

    def test_xlsx_zero_results_opens(self, session):
        job = make_job(status="completed")
        session.add(job)
        session.commit()
        wb, _ = self._workbook(session, job)
        assert wb.sheetnames == ["Leads", "Research Summary", "Parameters"]
        assert wb["Leads"].max_row == 1  # header only


# ---------------------------------------------------------------------------
# filenames
# ---------------------------------------------------------------------------


class TestExportFilename:
    def test_filename_convention(self, session):
        job = _completed_job_with_results(session, n=1)
        name = export_service.export_filename(job, "xlsx")
        short = job.id.replace("-", "")[:8]
        assert name == f"leadforge_jewelry_stores_{short}.xlsx"
        assert export_service.export_filename(job, "csv").endswith(".csv")

    def test_filename_sanitizes_industry(self, session):
        job = make_job(industry="Jewelry Stores & Repair (CA)!")
        session.add(job)
        session.commit()
        name = export_service.export_filename(job, "xlsx")
        assert name.startswith("leadforge_jewelry_stores_repair_ca_")
        assert all(c.isalnum() or c in "_.-" for c in name)

    def test_filename_rejects_unknown_format(self, session):
        job = make_job()
        session.add(job)
        session.commit()
        with pytest.raises(ValueError):
            export_service.export_filename(job, "pdf")


# ---------------------------------------------------------------------------
# API
# ---------------------------------------------------------------------------


def _wait_completed(client, job_id, timeout_s=15.0):
    deadline = time.time() + timeout_s
    while time.time() < deadline:
        job = client.get(f"/api/research/jobs/{job_id}").json()
        if job["status"] in ("completed", "failed"):
            return job
        time.sleep(0.05)
    raise TimeoutError(f"job {job_id} did not finish")


class TestExportApi:
    def test_csv_export_download(self, client):
        resp = client.post(
            "/api/research/jobs",
            json={
                "industry": "Jewelry Stores",
                "country": "United States",
                "requested_leads": 10,
                "demo_delay_ms": 0,
            },
        )
        assert resp.status_code == 202
        job_id = resp.json()["id"]
        job = _wait_completed(client, job_id)
        assert job["status"] == "completed"

        resp = client.post(f"/api/research/jobs/{job_id}/export?format=csv")
        assert resp.status_code == 200
        assert resp.headers["content-type"].startswith("text/csv")
        disp = resp.headers["content-disposition"]
        assert disp.startswith("attachment;")
        assert disp.endswith('.csv"')
        assert "leadforge_jewelry_stores_" in disp
        assert resp.content.startswith(b"\xef\xbb\xbf")
        rows = list(csv.DictReader(io.StringIO(resp.content.decode("utf-8-sig"))))
        assert len(rows) == job["accepted"]
        assert list(rows[0].keys()) == list(export_service.EXPORT_COLUMNS)

    def test_xlsx_export_download(self, client):
        resp = client.post(
            "/api/research/jobs",
            json={
                "industry": "Jewelry Stores",
                "country": "United States",
                "requested_leads": 10,
                "demo_delay_ms": 0,
            },
        )
        assert resp.status_code == 202
        job_id = resp.json()["id"]
        job = _wait_completed(client, job_id)
        assert job["status"] == "completed"

        resp = client.post(f"/api/research/jobs/{job_id}/export?format=xlsx")
        assert resp.status_code == 200
        assert (
            resp.headers["content-type"]
            == "application/vnd.openxmlformats-officedocument.spreadsheetml.sheet"
        )
        disp = resp.headers["content-disposition"]
        assert disp.startswith("attachment;")
        assert disp.endswith('.xlsx"')
        wb = load_workbook(io.BytesIO(resp.content))
        assert wb.sheetnames == ["Leads", "Research Summary", "Parameters"]
        assert wb["Leads"].max_row - 1 == job["accepted"]

    def test_export_missing_job_404(self, client):
        resp = client.post("/api/research/jobs/does-not-exist/export?format=csv")
        assert resp.status_code == 404
        assert resp.json()["code"] == "job_not_found"

    def test_export_invalid_format_422(self, client):
        resp = client.post(
            "/api/research/jobs",
            json={
                "industry": "Jewelry Stores",
                "country": "United States",
                "requested_leads": 10,
                "demo_delay_ms": 0,
            },
        )
        job_id = resp.json()["id"]
        _wait_completed(client, job_id)
        resp = client.post(f"/api/research/jobs/{job_id}/export?format=pdf")
        assert resp.status_code == 422

    def test_export_non_completed_job_409(self, client, engine):
        # Insert a queued job directly: with TestClient, background tasks run
        # to completion inside the create POST, so a queued job cannot be
        # observed by racing the API.
        with session_scope(engine) as session:
            job = make_job(status="queued", industry="Jewelry Stores")
            session.add(job)
            session.commit()
            job_id = job.id
        resp = client.post(f"/api/research/jobs/{job_id}/export?format=csv")
        assert resp.status_code == 409
        assert resp.json()["code"] == "job_not_runnable"

    def test_export_zero_results(self, client, engine):
        # Completed job with no results: valid empty export.
        with session_scope(engine) as session:
            job = make_job(status="completed", industry="Jewelry Stores")
            session.add(job)
            session.commit()
            job_id = job.id
        resp = client.post(f"/api/research/jobs/{job_id}/export?format=csv")
        assert resp.status_code == 200
        rows = list(csv.reader(io.StringIO(resp.content.decode("utf-8-sig"))))
        assert len(rows) == 1  # header only
        resp = client.post(f"/api/research/jobs/{job_id}/export?format=xlsx")
        assert resp.status_code == 200
        wb = load_workbook(io.BytesIO(resp.content))
        assert wb["Leads"].max_row == 1


# ---------------------------------------------------------------------------
# CLI
# ---------------------------------------------------------------------------


class TestExportCli:
    def test_cli_export_csv_writes_file(self, engine, monkeypatch, tmp_path):
        monkeypatch.setattr("leadforge.db.get_engine", lambda: engine)
        with session_scope(engine) as session:
            job = _completed_job_with_results(session, n=2)
            job_id = job.id
        out = tmp_path / "leads.csv"
        rc = cli_module.main(
            ["export", "--job", job_id, "--format", "csv", "--out", str(out)]
        )
        assert rc == 0
        assert out.exists()
        content = out.read_bytes()
        assert content.startswith(b"\xef\xbb\xbf")
        rows = list(csv.DictReader(io.StringIO(content.decode("utf-8-sig"))))
        assert len(rows) == 2

    def test_cli_export_xlsx_writes_file(self, engine, monkeypatch, tmp_path):
        monkeypatch.setattr("leadforge.db.get_engine", lambda: engine)
        with session_scope(engine) as session:
            job = _completed_job_with_results(session, n=2)
            job_id = job.id
        out = tmp_path / "leads.xlsx"
        rc = cli_module.main(
            ["export", "--job", job_id, "--format", "xlsx", "--out", str(out)]
        )
        assert rc == 0
        wb = load_workbook(out)
        assert wb.sheetnames == ["Leads", "Research Summary", "Parameters"]
        assert wb["Leads"].max_row == 3  # header + 2 rows

    def test_cli_export_missing_job_fails(self, engine, monkeypatch, tmp_path, capsys):
        monkeypatch.setattr("leadforge.db.get_engine", lambda: engine)
        rc = cli_module.main(
            ["export", "--job", "no-such-job", "--out", str(tmp_path / "x.csv")]
        )
        assert rc == 1
        assert "no research job" in capsys.readouterr().out

    def test_cli_export_non_completed_job_fails(
        self, engine, monkeypatch, tmp_path, capsys
    ):
        monkeypatch.setattr("leadforge.db.get_engine", lambda: engine)
        with session_scope(engine) as session:
            job = make_job(status="running")
            session.add(job)
            session.commit()
            job_id = job.id
        rc = cli_module.main(
            ["export", "--job", job_id, "--out", str(tmp_path / "x.csv")]
        )
        assert rc == 1
        assert "only completed jobs" in capsys.readouterr().out
